[package]
name = "cubers"
version = "0.1.0"
authors = ["cookie-s <cookie-s@users.noreply.github.com>"]
edition = "2018"

[dependencies]
strum = "0.15"
strum_macros = "0.15"
num-traits = "0.2"
num-derive = "0.2"
lazy_static = "1.3.0"
